/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene_room_nc.glb -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene_room_nc.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="GroupBackpack" position={[-1.77, 0.219, -1.073]} rotation={[0, 1.158, 0]}>
          <group name="Backpack" position={[0.48, 0, 0.811]} rotation={[-Math.PI / 2, 0, 1.509]}>
            <mesh name="Backpack_1" geometry={nodes.Backpack_1.geometry} material={materials.DarkBrown} />
            <mesh name="Backpack_2" geometry={nodes.Backpack_2.geometry} material={materials.Brown} />
            <mesh name="Backpack_3" geometry={nodes.Backpack_3.geometry} material={materials.Gold} />
          </group>
        </group>
        <group name="GroupDesk" position={[-0.009, -0.013, -1.931]} rotation={[-Math.PI, 1.567, -Math.PI]}>
          <group name="GroupeComputerDesk" position={[-1.931, 0.375, 0.001]} rotation={[Math.PI, -1.567, Math.PI]}>
            <mesh name="ComputerDesk1" geometry={nodes.ComputerDesk1.geometry} material={materials['DarkWood.012']} position={[0.133, -0.055, -1.567]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          </group>
          <group name="Chair" position={[-1.321, 0.697, 0.441]} rotation={[-Math.PI / 2, 0, 1.643]}>
            <mesh name="Chair_1" geometry={nodes.Chair_1.geometry} material={materials['Executive.003']} />
            <mesh name="Chair_2" geometry={nodes.Chair_2.geometry} material={materials['Executive__1.003']} />
            <mesh name="Chair_3" geometry={nodes.Chair_3.geometry} material={materials.Executive__2} />
            <mesh name="Chair_4" geometry={nodes.Chair_4.geometry} material={materials['Executive__3.003']} />
          </group>
          <mesh name="ComputerMouse_mesh" geometry={nodes.ComputerMouse_mesh.geometry} material={materials['ComputerMouse_mat1.001']} position={[-0.583, 0.805, 0.693]} rotation={[-Math.PI, 1.532, -Math.PI]} />
          <group name="Cylinder" position={[-0.249, 1.317, 0.103]} rotation={[0, -1.325, 0]}>
            <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials['Grey.002']} />
            <mesh name="Cylinder_2" geometry={nodes.Cylinder_2.geometry} material={materials.Dark} />
            <mesh name="Cylinder_3" geometry={nodes.Cylinder_3.geometry} material={materials.Blue} />
            <mesh name="Cylinder_4" geometry={nodes.Cylinder_4.geometry} material={materials['Material.005']} />
          </group>
          <group name="GroupGamingComputer" position={[-0.369, 0.308, 1.121]} rotation={[0, -0.004, 0]}>
            <mesh name="mesh549538436" geometry={nodes.mesh549538436.geometry} material={materials.mat23} />
            <mesh name="mesh549538436_1" geometry={nodes.mesh549538436_1.geometry} material={materials['mat8.003']} />
            <mesh name="mesh549538436_2" geometry={nodes.mesh549538436_2.geometry} material={materials['mat24.001']} />
            <mesh name="mesh549538436_3" geometry={nodes.mesh549538436_3.geometry} material={materials['mat17.003']} />
            <mesh name="mesh549538436_4" geometry={nodes.mesh549538436_4.geometry} material={materials['mat16.001']} />
            <mesh name="mesh549538436_5" geometry={nodes.mesh549538436_5.geometry} material={materials['mat21.008']} />
            <mesh name="mesh549538436_6" geometry={nodes.mesh549538436_6.geometry} material={materials['mat3.002']} />
            <mesh name="mesh549538436_7" geometry={nodes.mesh549538436_7.geometry} material={materials['mat10.001']} />
            <mesh name="mesh549538436_8" geometry={nodes.mesh549538436_8.geometry} material={materials['mat9.002']} />
            <mesh name="mesh549538436_9" geometry={nodes.mesh549538436_9.geometry} material={materials['mat15.002']} />
            <mesh name="mesh549538436_10" geometry={nodes.mesh549538436_10.geometry} material={materials.mat22} />
            <mesh name="mesh549538436_11" geometry={nodes.mesh549538436_11.geometry} material={materials['mat11.001']} />
            <mesh name="mesh549538436_12" geometry={nodes.mesh549538436_12.geometry} material={materials['mat12.002']} />
            <mesh name="mesh549538436_13" geometry={nodes.mesh549538436_13.geometry} material={materials['mat5.003']} />
            <mesh name="mesh549538436_14" geometry={nodes.mesh549538436_14.geometry} material={materials['mat13.002']} />
            <mesh name="mesh549538436_15" geometry={nodes.mesh549538436_15.geometry} material={materials['mat2.001']} />
          </group>
          <mesh name="Keyboard-aPwr5p1dluw" geometry={nodes['Keyboard-aPwr5p1dluw'].geometry} material={materials.mat23} position={[-0.555, 0.792, 0.35]} rotation={[-1.571, 0.042, -1.504]} scale={0.931} />
          <group name="Light_Desk" position={[-0.142, 1.048, 1.156]} rotation={[-Math.PI / 2, 0, 1.123]}>
            <mesh name="Light_Desk_1" geometry={nodes.Light_Desk_1.geometry} material={materials['Black.097']} />
            <mesh name="Light_Desk_2" geometry={nodes.Light_Desk_2.geometry} material={materials['LightMetal.027']} />
            <mesh name="Light_Desk_3" geometry={nodes.Light_Desk_3.geometry} material={materials['White.053']} />
          </group>
          <mesh name="Mousepad002" geometry={nodes.Mousepad002.geometry} material={materials['Mousepad.001']} position={[-0.581, 0.807, 0.598]} />
          <group name="Rubiks" position={[-0.053, 0.843, 1.001]} rotation={[0, -1.083, 0]}>
            <mesh name="pCube37_1" geometry={nodes.pCube37_1.geometry} material={materials.blinn9SG} />
            <mesh name="pCube37_1_1" geometry={nodes.pCube37_1_1.geometry} material={materials.blinn2SG} />
            <mesh name="pCube37_1_2" geometry={nodes.pCube37_1_2.geometry} material={materials.blinn11SG} />
            <mesh name="pCube37_1_3" geometry={nodes.pCube37_1_3.geometry} material={materials.blinn4SG} />
            <mesh name="pCube37_1_4" geometry={nodes.pCube37_1_4.geometry} material={materials.blinn6SG} />
            <mesh name="pCube37_1_5" geometry={nodes.pCube37_1_5.geometry} material={materials.blinn7SG} />
            <mesh name="pCube37_1_6" geometry={nodes.pCube37_1_6.geometry} material={materials.blinn5SG} />
          </group>
        </group>
        <group name="GroupPhone" position={[-0.064, 0.922, -1.37]} rotation={[-1.571, 0, 0.316]}>
          <group name="Phone001" position={[0, 0.141, -0.127]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Phone001_1" geometry={nodes.Phone001_1.geometry} material={materials.White} />
            <mesh name="Phone001_2" geometry={nodes.Phone001_2.geometry} material={materials.Grey} />
            <mesh name="Phone001_3" geometry={nodes.Phone001_3.geometry} material={materials.Black} />
          </group>
        </group>
        <group name="GroupCeiling" position={[-0.004, 2.488, -0.502]} />
        <group name="GroupTelescop" position={[-1.109, 0, -0.486]} rotation={[0, -0.918, 0]} />
        <group name="GroupBigBooks" position={[1.901, 0.299, -1.512]} />
        <group name="GroupUnderMug" position={[1.001, 0.806, -1.579]}>
          <mesh name="Mousepad" geometry={nodes.Mousepad.geometry} material={materials.metalDark} position={[0, -0.013, 0]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="GroupStickyBoard" position={[2.175, 1.419, -1.962]} rotation={[3.067, 0, 0]}>
          <mesh name="Sticky_notes" geometry={nodes.Sticky_notes.geometry} material={materials['03___Default.001']} position={[0, -0.001, 0.016]} rotation={[-3.044, 0.045, 3.138]} />
        </group>
        <group name="RootNode" position={[-1.497, 0, -1.397]} rotation={[0, -0.93, 0]} scale={1.102}>
          <mesh name="Telescope001" geometry={nodes.Telescope001.geometry} material={materials.Material} position={[0.088, 0, 0.006]} rotation={[0, 0.149, 0]} scale={112.257} />
        </group>
        <group name="RootNode001" position={[0, 2.403, -0.473]} scale={1.29}>
          <mesh name="Ceiling_Fan001" geometry={nodes.Ceiling_Fan001.geometry} material={materials['Material.002']} scale={100} />
        </group>
        <group name="RootNode002" position={[2.031, 0.372, -1.258]}>
          <mesh name="Books001" geometry={nodes.Books001.geometry} material={materials['Material.003']} position={[-0.128, -0.074, -0.257]} scale={138.225} />
        </group>
        <group name="GroupDualScreen" position={[0.377, 1.25, -1.528]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh name="mesh329542522001" geometry={nodes.mesh329542522001.geometry} material={materials['mat22.001']} />
          <mesh name="mesh329542522001_1" geometry={nodes.mesh329542522001_1.geometry} material={materials['mat23.001']} />
          <mesh name="mesh329542522001_2" geometry={nodes.mesh329542522001_2.geometry} material={materials['mat21.002']} />
        </group>
        <group name="GroupWhiteBoard" position={[2.216, 0.934, -2.006]}>
          <mesh name="White_board_Cube045_1" geometry={nodes.White_board_Cube045_1.geometry} material={materials.FFFFFF} />
          <mesh name="White_board_Cube045_1_1" geometry={nodes.White_board_Cube045_1_1.geometry} material={materials.F44336} />
        </group>
        <group name="Carpet" position={[3.281, -0.013, -0.134]} rotation={[0, -0.193, 0]}>
          <mesh name="Box002_1" geometry={nodes.Box002_1.geometry} material={materials['_crayfishdiffuse.001']} />
          <mesh name="Box002_1_1" geometry={nodes.Box002_1_1.geometry} material={materials['03___Default.001']} />
          <mesh name="Box002_1_2" geometry={nodes.Box002_1_2.geometry} material={materials['07___Default']} />
          <mesh name="Box002_1_3" geometry={nodes.Box002_1_3.geometry} material={materials['08___Default.001']} />
          <mesh name="Box002_1_4" geometry={nodes.Box002_1_4.geometry} material={materials['02___Default.001']} />
        </group>
        <group name="GroupShelf" position={[2.414, 0.446, -1.567]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh name="mesh1329329239" geometry={nodes.mesh1329329239.geometry} material={materials['DarkWood.012']} />
          <mesh name="mesh1329329239_1" geometry={nodes.mesh1329329239_1.geometry} material={materials.mat9} />
          <mesh name="mesh1329329239_2" geometry={nodes.mesh1329329239_2.geometry} material={materials.mat13} />
          <mesh name="mesh1329329239_3" geometry={nodes.mesh1329329239_3.geometry} material={materials.mat5} />
          <mesh name="mesh1329329239_4" geometry={nodes.mesh1329329239_4.geometry} material={materials.mat2} />
          <mesh name="mesh1329329239_5" geometry={nodes.mesh1329329239_5.geometry} material={materials.mat8} />
          <mesh name="mesh1329329239_6" geometry={nodes.mesh1329329239_6.geometry} material={materials.mat7} />
          <mesh name="mesh1329329239_7" geometry={nodes.mesh1329329239_7.geometry} material={materials.mat12} />
          <mesh name="mesh1329329239_8" geometry={nodes.mesh1329329239_8.geometry} material={materials['mat18.001']} />
        </group>
        <group name="Mug" position={[0.989, 0.795, -1.639]} rotation={[0, -0.548, 0]}>
          <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials['02___Default.002']} />
          <mesh name="Cylinder001_1_1" geometry={nodes.Cylinder001_1_1.geometry} material={materials['01___Default']} />
          <mesh name="Cylinder001_1_2" geometry={nodes.Cylinder001_1_2.geometry} material={materials['01___Default-2']} />
          <mesh name="Cylinder001_1_3" geometry={nodes.Cylinder001_1_3.geometry} material={materials['02___Default-2']} />
          <mesh name="Cylinder001_1_4" geometry={nodes.Cylinder001_1_4.geometry} material={materials['07___Default.001']} />
        </group>
        <group name="GroupBookStack" position={[2.747, 0.092, -1.559]} rotation={[-Math.PI, 0.986, -Math.PI]}>
          <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={materials.mat10} />
          <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={materials['mat23.003']} />
          <mesh name="Node-Mesh002_2" geometry={nodes['Node-Mesh002_2'].geometry} material={materials['mat21.004']} />
          <mesh name="Node-Mesh002_3" geometry={nodes['Node-Mesh002_3'].geometry} material={materials.mat4} />
          <mesh name="Node-Mesh002_4" geometry={nodes['Node-Mesh002_4'].geometry} material={materials['mat8.001']} />
          <mesh name="Node-Mesh002_5" geometry={nodes['Node-Mesh002_5'].geometry} material={materials['mat5.001']} />
          <mesh name="Node-Mesh002_6" geometry={nodes['Node-Mesh002_6'].geometry} material={materials.mat3} />
          <mesh name="Node-Mesh002_7" geometry={nodes['Node-Mesh002_7'].geometry} material={materials.mat17} />
          <mesh name="Node-Mesh002_8" geometry={nodes['Node-Mesh002_8'].geometry} material={materials.mat16} />
          <mesh name="Node-Mesh002_9" geometry={nodes['Node-Mesh002_9'].geometry} material={materials.mat1} />
        </group>
        <group name="GroupStapler" position={[-0.265, 0.795, -1.833]} rotation={[-Math.PI, 0.304, 0]}>
          <mesh name="Box001_1" geometry={nodes.Box001_1.geometry} material={materials['_crayfishdiffuse.002']} />
          <mesh name="Box001_1_1" geometry={nodes.Box001_1_1.geometry} material={materials['02___Default.003']} />
        </group>
        <group name="GroupPens" position={[0.189, 0.795, -0.882]}>
          <mesh name="Cylinder006_1" geometry={nodes.Cylinder006_1.geometry} material={materials['_crayfishdiffuse.003']} />
          <mesh name="Cylinder006_1_1" geometry={nodes.Cylinder006_1_1.geometry} material={materials['08___Default.003']} />
          <mesh name="Cylinder006_1_2" geometry={nodes.Cylinder006_1_2.geometry} material={materials['03___Default.002']} />
          <mesh name="Cylinder006_1_3" geometry={nodes.Cylinder006_1_3.geometry} material={materials['02___Default.004']} />
          <mesh name="Cylinder006_1_4" geometry={nodes.Cylinder006_1_4.geometry} material={materials['09___Default.001']} />
          <mesh name="Cylinder006_1_5" geometry={nodes.Cylinder006_1_5.geometry} material={materials['07___Default.002']} />
        </group>
        <group name="GroupBinder" position={[2.274, 0.009, -1.53]} rotation={[0, 1.508, 0]}>
          <mesh name="Binder_Cube-Mesh" geometry={nodes['Binder_Cube-Mesh'].geometry} material={materials.blinn7SG} />
          <mesh name="Binder_Cube-Mesh_1" geometry={nodes['Binder_Cube-Mesh_1'].geometry} material={materials.Sticker} />
          <mesh name="Binder_Cube-Mesh_2" geometry={nodes['Binder_Cube-Mesh_2'].geometry} material={materials.Holder} />
          <mesh name="Binder_Cube-Mesh_3" geometry={nodes['Binder_Cube-Mesh_3'].geometry} material={materials.Metal} />
          <group name="GroupBinder001" position={[0.006, 0, 0.089]}>
            <mesh name="Binder_Cube-Mesh002" geometry={nodes['Binder_Cube-Mesh002'].geometry} material={materials.blinn9SG} />
            <mesh name="Binder_Cube-Mesh002_1" geometry={nodes['Binder_Cube-Mesh002_1'].geometry} material={materials['Sticker.002']} />
            <mesh name="Binder_Cube-Mesh002_2" geometry={nodes['Binder_Cube-Mesh002_2'].geometry} material={materials['Holder.002']} />
            <mesh name="Binder_Cube-Mesh002_3" geometry={nodes['Binder_Cube-Mesh002_3'].geometry} material={materials['Metal.002']} />
          </group>
          <group name="GroupBinder002" position={[0.008, 0, 0.134]}>
            <mesh name="Binder_Cube-Mesh003" geometry={nodes['Binder_Cube-Mesh003'].geometry} material={materials.blinn5SG} />
            <mesh name="Binder_Cube-Mesh003_1" geometry={nodes['Binder_Cube-Mesh003_1'].geometry} material={materials['Sticker.003']} />
            <mesh name="Binder_Cube-Mesh003_2" geometry={nodes['Binder_Cube-Mesh003_2'].geometry} material={materials['Holder.003']} />
            <mesh name="Binder_Cube-Mesh003_3" geometry={nodes['Binder_Cube-Mesh003_3'].geometry} material={materials['Metal.003']} />
          </group>
          <group name="GroupBinder003" position={[0.011, 0, 0.178]}>
            <mesh name="Binder_Cube-Mesh004" geometry={nodes['Binder_Cube-Mesh004'].geometry} material={materials.blinn7SG} />
            <mesh name="Binder_Cube-Mesh004_1" geometry={nodes['Binder_Cube-Mesh004_1'].geometry} material={materials['Sticker.004']} />
            <mesh name="Binder_Cube-Mesh004_2" geometry={nodes['Binder_Cube-Mesh004_2'].geometry} material={materials['Holder.004']} />
            <mesh name="Binder_Cube-Mesh004_3" geometry={nodes['Binder_Cube-Mesh004_3'].geometry} material={materials['Metal.004']} />
          </group>
          <group name="GroupBinder004" position={[0.014, 0, 0.222]}>
            <mesh name="Binder_Cube-Mesh005" geometry={nodes['Binder_Cube-Mesh005'].geometry} material={materials.blinn2SG} />
            <mesh name="Binder_Cube-Mesh005_1" geometry={nodes['Binder_Cube-Mesh005_1'].geometry} material={materials['Sticker.005']} />
            <mesh name="Binder_Cube-Mesh005_2" geometry={nodes['Binder_Cube-Mesh005_2'].geometry} material={materials['Holder.005']} />
            <mesh name="Binder_Cube-Mesh005_3" geometry={nodes['Binder_Cube-Mesh005_3'].geometry} material={materials['Metal.005']} />
          </group>
          <group name="GroupBinder005" position={[0.016, 0, 0.264]}>
            <mesh name="Binder_Cube-Mesh006" geometry={nodes['Binder_Cube-Mesh006'].geometry} material={materials.Brown} />
            <mesh name="Binder_Cube-Mesh006_1" geometry={nodes['Binder_Cube-Mesh006_1'].geometry} material={materials['Sticker.006']} />
            <mesh name="Binder_Cube-Mesh006_2" geometry={nodes['Binder_Cube-Mesh006_2'].geometry} material={materials['Holder.006']} />
            <mesh name="Binder_Cube-Mesh006_3" geometry={nodes['Binder_Cube-Mesh006_3'].geometry} material={materials['Metal.006']} />
          </group>
          <group name="GroupBinder006" position={[0.003, 0, 0.045]}>
            <mesh name="Binder_Cube-Mesh007" geometry={nodes['Binder_Cube-Mesh007'].geometry} material={materials['Binder_Blue.007']} />
            <mesh name="Binder_Cube-Mesh007_1" geometry={nodes['Binder_Cube-Mesh007_1'].geometry} material={materials['Sticker.007']} />
            <mesh name="Binder_Cube-Mesh007_2" geometry={nodes['Binder_Cube-Mesh007_2'].geometry} material={materials['Holder.007']} />
            <mesh name="Binder_Cube-Mesh007_3" geometry={nodes['Binder_Cube-Mesh007_3'].geometry} material={materials['Metal.007']} />
          </group>
        </group>
        <mesh name="GroupPaperOnDesk" geometry={nodes.GroupPaperOnDesk.geometry} material={materials['02___Default.005']} position={[0.366, 0.728, -1.67]}>
          <mesh name="Box002001" geometry={nodes.Box002001.geometry} material={materials['02___Default.005']} />
          <mesh name="Box003001" geometry={nodes.Box003001.geometry} material={materials['02___Default.005']} />
        </mesh>
        <mesh name="Paper001" geometry={nodes.Paper001.geometry} material={materials['Mat.002']} position={[-0.334, 0.791, -1.565]} rotation={[-Math.PI, 1.319, -Math.PI]} />
        <group name="GroupSwitchLights" position={[3.449, 1.038, -1.992]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.mat21} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat15} />
        </group>
        <mesh name="GroupStickyNotes" geometry={nodes.GroupStickyNotes.geometry} material={materials['0.BaseMaterial']} position={[1.932, -0.475, -1.343]} rotation={[-0.098, -0.003, 0.027]} />
        <group name="GroupArtWall" position={[-0.934, 1.685, -1.992]} rotation={[-Math.PI, 0, Math.PI / 2]}>
          <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials['mat23.006']} />
          <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['mat21.009']} />
          <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={materials['mat24.002']} />
          <mesh name="Node-Mesh001_3" geometry={nodes['Node-Mesh001_3'].geometry} material={materials['mat25.001']} />
        </group>
        <group name="GroupArtWall001" position={[-0.934, 1.362, -1.992]} rotation={[-Math.PI, 0, Math.PI / 2]}>
          <mesh name="Node-Mesh004" geometry={nodes['Node-Mesh004'].geometry} material={materials['mat23.007']} />
          <mesh name="Node-Mesh004_1" geometry={nodes['Node-Mesh004_1'].geometry} material={materials['mat21.010']} />
          <mesh name="Node-Mesh004_2" geometry={nodes['Node-Mesh004_2'].geometry} material={materials['mat24.003']} />
          <mesh name="Node-Mesh004_3" geometry={nodes['Node-Mesh004_3'].geometry} material={materials['mat25.002']} />
        </group>
        <group name="GooglepCube51" position={[-0.25, 0.324, -1.532]} rotation={[-1.889, -0.056, -1.4]}>
          <mesh name="GooglepCube51_1" geometry={nodes.GooglepCube51_1.geometry} material={materials['Google:blinn1SG']} />
          <mesh name="GooglepCube51_1_1" geometry={nodes.GooglepCube51_1_1.geometry} material={materials.blinn3SG} />
          <mesh name="GooglepCube51_1_2" geometry={nodes.GooglepCube51_1_2.geometry} material={materials['Ambulance_01:blinn3SG']} />
        </group>
        <group name="Light_Bulb2" position={[1.121, 1.193, -1.75]} rotation={[-2.638, -1.277, 1.405]}>
          <mesh name="Light_Bulb2-Mesh" geometry={nodes['Light_Bulb2-Mesh'].geometry} material={materials.metal006} />
          <mesh name="Light_Bulb2-Mesh_1" geometry={nodes['Light_Bulb2-Mesh_1'].geometry} material={materials['Mat.004']} />
        </group>
        <mesh name="CoffePlant_mehs001" geometry={nodes.CoffePlant_mehs001.geometry} material={materials['CoffeePlant_mat.002']} position={[1.549, 0, -1.57]} rotation={[0, 0.713, 0]} scale={0.091} />
        <mesh name="Xbox_Controller001" geometry={nodes.Xbox_Controller001.geometry} material={materials.Mat} position={[1.522, 0.041, -1.34]} rotation={[0, 0.208, 0]} scale={0.006} />
        <mesh name="Analog_Cock001" geometry={nodes.Analog_Cock001.geometry} material={materials['Mat.005']} position={[0.376, 1.626, -1.973]} rotation={[0, -Math.PI / 2, 0]} scale={0.016} />
        <mesh name="UmbrellaPalmTree_mesh001" geometry={nodes.UmbrellaPalmTree_mesh001.geometry} material={materials['UmbrellaPalmTree_mat.001']} position={[3.137, 0.563, -1.661]} scale={0.059} />
        <mesh name="Screen1" geometry={nodes.Screen1.geometry} material={materials['mat22.001']} position={[0.377, 1.25, -1.528]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Screen2" geometry={nodes.Screen2.geometry} material={materials['mat22.001']} position={[0.377, 1.25, -1.528]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="FaceArtWall1" geometry={nodes.FaceArtWall1.geometry} material={materials['mat15.003']} position={[-0.934, 1.685, -1.992]} rotation={[-Math.PI, 0, Math.PI / 2]} />
        <mesh name="FaceArtWall2" geometry={nodes.FaceArtWall2.geometry} material={materials['mat15.004']} position={[-0.934, 1.362, -1.992]} rotation={[-Math.PI, 0, Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene_room_nc.glb')
