/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene_experience.glb -K -k 
*/

import React, { useRef } from 'react'
import * as THREE from 'three';
import { useGLTF, useTexture } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { animate, useMotionValue } from "framer-motion";
import { useFrame } from "@react-three/fiber";

export function Buildings(props) {

  const { section } = props;
  const { nodes, materials } = useGLTF('models/scene_experience.glb');
  const texture = useTexture("textures/lightmap_experiences.jpg");
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const delay = 2
  const duration = 0.6;

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Gaea21_title" position={[9.655, 0.52, -3.3]}>
          <motion.group position={[0, 1.5, 0]} animate={{y: section === 4 ? 0 : section === 5 ? -5 : 15, transition: { ease: "easeInOut", duration, y: { delay: delay, duration }} }} >
            <mesh name="Letter_A_Font_mat_0001" geometry={nodes.Letter_A_Font_mat_0001.geometry} material={materials.Font_mat} position={[-1.5, 0.243, 0]} />
          </motion.group>
          <motion.group position={[0, 1.5, 0]} animate={{y: section === 4 ? 0 : section === 5 ? -5 : 15, transition: { ease: "easeInOut", duration, y: { delay: delay+0.2, duration }} }} >
            <mesh name="Letter_A_Font_mat_0002" geometry={nodes.Letter_A_Font_mat_0002.geometry} material={materials.Font_mat} position={[-0.5, 0.243, 0]} />
          </motion.group>
          <motion.group position={[0, 1.5, 0]} animate={{y: section === 4 ? 0 : section === 5 ? -5 : 15, transition: { ease: "easeInOut", duration, y: { delay: delay+0.4, duration }} }} >
            <mesh name="Letter_E_Font_mat_0001" geometry={nodes.Letter_E_Font_mat_0001.geometry} material={materials.Font_mat} position={[-1, 0.243, 0]} />
          </motion.group>
          <motion.group position={[0, 1.5, 0]} animate={{y: section === 4 ? 0 : section === 5 ? -5 : 15, transition: { ease: "easeInOut", duration, y: { delay: delay+0.6, duration }} }} >
            <mesh name="Letter_G_Font_mat_0001" geometry={nodes.Letter_G_Font_mat_0001.geometry} material={materials.Font_mat} position={[-2, 0.243, 0]} />
          </motion.group>
          <motion.group position={[0, 1.5, 0]} animate={{y: section === 4 ? 0 : section === 5 ? -5 : 15, transition: { ease: "easeInOut", duration, y: { delay: delay+0.8, duration }} }} >
            <mesh name="Number_1_Font_mat_0001" geometry={nodes.Number_1_Font_mat_0001.geometry} material={materials.Font_mat} position={[0.6, 0.21, 0]} />
          </motion.group>
          <motion.group position={[0, 1.5, 0]} animate={{y: section === 4 ? 0 : section === 5 ? -5 : 15, transition: { ease: "easeInOut", duration, y: { delay: delay+1, duration }} }} >
            <mesh name="Number_2_Font_mat_0001" geometry={nodes.Number_2_Font_mat_0001.geometry} material={materials.Font_mat} position={[0.1, 0.243, 0]} />
          </motion.group>
        </group>
        <group name="RootNode003" position={[64.387, 0, 0]}>
          <group name="Building4" position={[26.636, 0, 0.076]} rotation={[-Math.PI / 2, 0, -0.676]} scale={100}>
            <mesh name="Building4_1" geometry={nodes.Building4_1.geometry} material={materials.LightBlue} />
            <mesh name="Building4_2" geometry={nodes.Building4_2.geometry} material={materials.WhiteBlue} />
            <mesh name="Building4_3" geometry={nodes.Building4_3.geometry} material={materials.GreyBlue} />
            <mesh name="Building4_4" geometry={nodes.Building4_4.geometry} material={materials['White.001']} />
            <mesh name="Building4_5" geometry={nodes.Building4_5.geometry} material={materials['Grey.001']} />
            <mesh name="Building4_6" geometry={nodes.Building4_6.geometry} material={materials['Brown.001']} />
            <mesh name="Building4_7" geometry={nodes.Building4_7.geometry} material={materials.DarkGrey} />
          </group>
        </group>
        <group name="RootNode004" position={[25.452, 0, 0]}>
          <group name="House1" position={[-19.626, 3.49, -7.456]} rotation={[-Math.PI / 2, 0, 0.824]} scale={100}>
            <mesh name="House1_1" geometry={nodes.House1_1.geometry} material={materials['Grey.003']} />
            <mesh name="House1_2" geometry={nodes.House1_2.geometry} material={materials['DarkGrey.001']} />
            <mesh name="House1_3" geometry={nodes.House1_3.geometry} material={materials['Brown.002']} />
            <mesh name="House1_4" geometry={nodes.House1_4.geometry} material={materials['White.002']} />
          </group>
        </group>
        <group name="RootNode005" position={[59.173, 0.969, 4.26]}>
          <group name="Building3_Big" position={[4.928, 1.9, -9.831]} rotation={[-Math.PI / 2, 0, -0.703]} scale={100}>
            <mesh name="Building3_Big_1" geometry={nodes.Building3_Big_1.geometry} material={materials.BrickRed} />
            <mesh name="Building3_Big_2" geometry={nodes.Building3_Big_2.geometry} material={materials.Beige} />
            <mesh name="Building3_Big_3" geometry={nodes.Building3_Big_3.geometry} material={materials.LightYellow} />
            <mesh name="Building3_Big_4" geometry={nodes.Building3_Big_4.geometry} material={materials['Brown.003']} />
            <mesh name="Building3_Big_5" geometry={nodes.Building3_Big_5.geometry} material={materials['DarkGrey.002']} />
            <mesh name="Building3_Big_6" geometry={nodes.Building3_Big_6.geometry} material={materials['Grey.004']} />
          </group>
        </group>
        <group name="RootNode006" position={[45.541, 0.308, 10.575]}>
          <group name="Building1_Small" position={[-10.948, 4.462, -17.595]} rotation={[-Math.PI / 2, 0, -0.731]} scale={100}>
            <mesh name="Building1_Small_1" geometry={nodes.Building1_Small_1.geometry} material={materials.DarkRed} />
            <mesh name="Building1_Small_2" geometry={nodes.Building1_Small_2.geometry} material={materials['Brown.004']} />
            <mesh name="Building1_Small_3" geometry={nodes.Building1_Small_3.geometry} material={materials['Beige.001']} />
            <mesh name="Building1_Small_4" geometry={nodes.Building1_Small_4.geometry} material={materials['Grey.005']} />
            <mesh name="Building1_Small_5" geometry={nodes.Building1_Small_5.geometry} material={materials['White.003']} />
            <mesh name="Building1_Small_6" geometry={nodes.Building1_Small_6.geometry} material={materials['LightYellow.001']} />
            <mesh name="Building1_Small_7" geometry={nodes.Building1_Small_7.geometry} material={materials['DarkGrey.003']} />
          </group>
        </group>
        <group name="Gaea21_role" position={[9.655, 0.033, -3.3]}>
          <mesh name="Letter_a_Font_mat_0001" geometry={nodes.Letter_a_Font_mat_0001.geometry} material={materials.Font_mat} position={[0.4, -0.08, 0]} />
          <mesh name="Letter_c_Font_mat_0001" geometry={nodes.Letter_c_Font_mat_0001.geometry} material={materials.Font_mat} position={[0.8, -0.08, 0]} />
          <mesh name="Letter_D_Font_mat_0001" geometry={nodes.Letter_D_Font_mat_0001.geometry} material={materials.Font_mat} position={[1.8, -0.05, 0]} />
          <mesh name="Letter_e_Font_mat_0001" geometry={nodes.Letter_e_Font_mat_0001.geometry} material={materials.Font_mat} position={[3, -0.08, 0]} />
          <mesh name="Letter_e_Font_mat_0002" geometry={nodes.Letter_e_Font_mat_0002.geometry} material={materials.Font_mat} position={[2.2, -0.08, 0]} />
          <mesh name="Letter_e_Font_mat_0003" geometry={nodes.Letter_e_Font_mat_0003.geometry} material={materials.Font_mat} position={[4.6, -0.08, 0]} />
          <mesh name="Letter_F_Font_mat_0001" geometry={nodes.Letter_F_Font_mat_0001.geometry} material={materials.Font_mat} position={[-2, 0, 0]} />
          <mesh name="Letter_k_Font_mat_0001" geometry={nodes.Letter_k_Font_mat_0001.geometry} material={materials.Font_mat} position={[1.2, -0.07, 0]} />
          <mesh name="Letter_l_Font_mat_0001" geometry={nodes.Letter_l_Font_mat_0001.geometry} material={materials.Font_mat} position={[3.4, -0.06, 0]} />
          <mesh name="Letter_l_Font_mat_0002" geometry={nodes.Letter_l_Font_mat_0002.geometry} material={materials.Font_mat} position={[-1.2, -0.07, 0]} />
          <mesh name="Letter_l_Font_mat_0003" geometry={nodes.Letter_l_Font_mat_0003.geometry} material={materials.Font_mat} position={[-0.8, -0.07, 0]} />
          <mesh name="Letter_o_Font_mat_0001" geometry={nodes.Letter_o_Font_mat_0001.geometry} material={materials.Font_mat} position={[3.8, -0.08, 0]} />
          <mesh name="Letter_p_Font_mat_0002" geometry={nodes.Letter_p_Font_mat_0002.geometry} material={materials.Font_mat} position={[4.2, -0.08, 0]} />
          <mesh name="Letter_r_Font_mat_0001" geometry={nodes.Letter_r_Font_mat_0001.geometry} material={materials.Font_mat} position={[5, -0.05, 0]} />
          <mesh name="Letter_s_Font_mat_0001" geometry={nodes.Letter_s_Font_mat_0001.geometry} material={materials.Font_mat} position={[-0.4, -0.09, 0]} />
          <mesh name="Letter_t_Font_mat_0001" geometry={nodes.Letter_t_Font_mat_0001.geometry} material={materials.Font_mat} position={[0, -0.03, 0]} />
          <mesh name="Letter_u_Font_mat_0001" geometry={nodes.Letter_u_Font_mat_0001.geometry} material={materials.Font_mat} position={[-1.6, -0.09, 0]} />
          <mesh name="Letter_v_Font_mat_0001" geometry={nodes.Letter_v_Font_mat_0001.geometry} material={materials.Font_mat} position={[2.6, -0.07, 0]} />
        </group>
        <group name="Gaea21_date" position={[9.655, -1.032, -3.3]}>
          <mesh name="Number_0_Font_mat_0001" geometry={nodes.Number_0_Font_mat_0001.geometry} material={materials.Font_mat} position={[-1.6, 0.318, 0]} />
          <mesh name="Number_0_Font_mat_0002" geometry={nodes.Number_0_Font_mat_0002.geometry} material={materials.Font_mat} position={[0.4, 0.318, 0]} />
          <mesh name="Number_2_Font_mat_0002" geometry={nodes.Number_2_Font_mat_0002.geometry} material={materials.Font_mat} position={[-2, 0.318, 0]} />
          <mesh name="Number_2_Font_mat_0003" geometry={nodes.Number_2_Font_mat_0003.geometry} material={materials.Font_mat} position={[-1.2, 0.318, 0]} />
          <mesh name="Number_2_Font_mat_0004" geometry={nodes.Number_2_Font_mat_0004.geometry} material={materials.Font_mat} position={[0, 0.318, 0]} />
          <mesh name="Number_2_Font_mat_0005" geometry={nodes.Number_2_Font_mat_0005.geometry} material={materials.Font_mat} position={[0.8, 0.318, 0]} />
          <mesh name="Number_3_Font_mat_0001" geometry={nodes.Number_3_Font_mat_0001.geometry} material={materials.Font_mat} position={[-0.8, 0.318, 0]} />
          <mesh name="Number_4_Font_mat_0001" geometry={nodes.Number_4_Font_mat_0001.geometry} material={materials.Font_mat} position={[1.2, 0.318, 0]} />
          <mesh name="Symbol_Dash_Font_mat_0001" geometry={nodes.Symbol_Dash_Font_mat_0001.geometry} material={materials.Font_mat} position={[-0.4, 0.318, 0]} />
        </group>
        <group name="GNextExp_title" position={[40.267, 0.52, -3.3]}>
          <mesh name="Letter_c_Font_mat_0002" geometry={nodes.Letter_c_Font_mat_0002.geometry} material={materials.Font_mat} position={[7, -0.08, 0]} />
          <mesh name="Letter_E_Font_mat_0002" geometry={nodes.Letter_E_Font_mat_0002.geometry} material={materials.Font_mat} position={[2.2, 0, 0]} />
          <mesh name="Letter_e_Font_mat_0004" geometry={nodes.Letter_e_Font_mat_0004.geometry} material={materials.Font_mat} position={[0.1, -0.08, 0]} />
          <mesh name="Letter_e_Font_mat_0005" geometry={nodes.Letter_e_Font_mat_0005.geometry} material={materials.Font_mat} position={[4, -0.08, 0]} />
          <mesh name="Letter_e_Font_mat_0006" geometry={nodes.Letter_e_Font_mat_0006.geometry} material={materials.Font_mat} position={[5.8, -0.08, 0]} />
          <mesh name="Letter_e_Font_mat_0007" geometry={nodes.Letter_e_Font_mat_0007.geometry} material={materials.Font_mat} position={[7.6, -0.08, 0]} />
          <mesh name="Letter_i_Font_mat_0001" geometry={nodes.Letter_i_Font_mat_0001.geometry} material={materials.Font_mat} position={[5.2, -0.08, 0]} />
          <mesh name="Letter_M_Font_mat_0001" geometry={nodes.Letter_M_Font_mat_0001.geometry} material={materials.Font_mat} position={[-2, 0, 0]} />
          <mesh name="Letter_N_Font_mat_0001" geometry={nodes.Letter_N_Font_mat_0001.geometry} material={materials.Font_mat} position={[-0.5, 0, 0]} />
          <mesh name="Letter_n_Font_mat_0001" geometry={nodes.Letter_n_Font_mat_0001.geometry} material={materials.Font_mat} position={[6.4, -0.08, 0]} />
          <mesh name="Letter_p_Font_mat_0001" geometry={nodes.Letter_p_Font_mat_0001.geometry} material={materials.Font_mat} position={[3.4, -0.08, 0]} />
          <mesh name="Letter_r_Font_mat_0002" geometry={nodes.Letter_r_Font_mat_0002.geometry} material={materials.Font_mat} position={[4.6, -0.04, 0]} />
          <mesh name="Letter_t_Font_mat_0002" geometry={nodes.Letter_t_Font_mat_0002.geometry} material={materials.Font_mat} position={[1.3, 0.01, 0]} />
          <mesh name="Letter_x_Font_mat_0001" geometry={nodes.Letter_x_Font_mat_0001.geometry} material={materials.Font_mat} position={[0.7, -0.08, 0]} />
          <mesh name="Letter_x_Font_mat_0002" geometry={nodes.Letter_x_Font_mat_0002.geometry} material={materials.Font_mat} position={[2.8, -0.08, 0]} />
          <mesh name="Letter_y_Font_mat_0001" geometry={nodes.Letter_y_Font_mat_0001.geometry} material={materials.Font_mat} position={[-1.4, -0.08, 0]} />
        </group>
        <group name="Tree1" position={[11.504, 4.257, -5.084]}>
          <mesh name="Tree1_1" geometry={nodes.Tree1_1.geometry} material={materials.BarkTree1} />
          <mesh name="Tree1_2" geometry={nodes.Tree1_2.geometry} material={materials.LeafTree1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/scene_experience.glb')
